FROM node:10

WORKDIR /DL_VIS
COPY . /DL_VIS

RUN npm install --registry https://repo.huaweicloud.com/repository/npm/ && \
    npm install --registry https://repo.huaweicloud.com/repository/npm/ serve -g && \
    npm run build
