FROM maven:3.6.3-jdk-8
WORKDIR usr/src/elkgraph
RUN mkdir -p /root/.m2 \
    && mkdir /root/.m2/repository
COPY settings.xml /root/.m2
COPY . .

RUN mvn clean package \
    && mv ./target/elkgraph-0.0.1-SNAPSHOT.jar app.jar